export interface Data {
    date:string
    gas:number
    electricDay:number
    electricNight:number
    dailyUsed:{gasD:number, dayD:number, nightD:number}
}

const data:Data[] = [
    {   
        
        date:"01/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"02/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"03/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"04/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"05/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"06/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"07/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"08/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"09/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"10/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"11/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"12/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"13/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"14/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"15/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"16/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"17/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"18/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"19/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"20/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"21/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"22/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"23/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"24/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"25/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"26/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"27/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"28/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"29/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"30/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
    {
        date:"31/12/2022",
        gas:0,
        electricDay:2,
        electricNight:3,
        dailyUsed:{
            gasD:0,
            dayD:0,
            nightD:0,
        }
    },
]


export default data